### ISSUE TITLE
Extraneous Back Button on Discover Search

### ISSUE THREAD

**Issue by edschema** [openedx/openedx-app-ios#640]
**Current Behavior**
On the Discovery page, if you click the search entry box, there are two back buttons. See screenshot:

<img width="275" height="247" alt="Image" src="https://github.com/user-attachments/assets/b31e45d2-661b-4771-a01d-1a065ae7cbee" />

**Desired Behavior**
Remove the lower 'back' arrow and keep only the "Discover" back button

**Comment by edschema** [comment]
**Initial Analysis**
The likely cause is duplicate navigation composition in the native iOS Discovery search flow. The Discover tab keeps the outer app navigation bar visible, which provides the desired native back affordance labeled from the previous Discover screen. When the user taps the fake search field, DiscoveryView routes to SearchView, and SearchView renders its own custom NavigationBar with a left back button. That custom in-content back button is the lower arrow the issue asks to remove.

The source evidence supports the issue's desired behavior: keep the native Discover back button and remove or suppress the custom NavigationBar back affordance in SearchView for this route. This is a UI bug, so the final claim still needs a screenshot/runtime check on the target build.

**Proposed Fix Shape (for review)**
1. Remove or conditionally suppress the custom NavigationBar in SearchView when SearchView is pushed from native Discovery and the outer navigation bar should own the back action.
2. Keep one back behavior: the native "Discover" navigation back should pop the pushed search controller.
3. Verify that the search text field still focuses automatically and is not covered by the native navigation bar.
4. Preserve accessibility: there should be one accessible Back button, not two controls with similar actions.
5. Add a screenshot/UI regression covering Discovery -> tap search field -> search screen.

**Comment by Demian-Yushyn** [comment]
Resolved - https://github.com/openedx/openedx-app-ios/pull/661

**Comment by edschema** [comment]
I pulled the changes in #661 but I'm still seeing the extraneous back button:

<img alt="Image" src="https://github.com/user-attachments/assets/2977a3ea-73d7-4d0f-b19d-d6710e480ca2" />

I closed #641 and #642
